### ISSUE TITLE
Need the KendoUI Slider for the Sample app

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#164] opened 2015-12-19 22:30 UTC
The **[KendoUI slider](http://demos.telerik.com/kendo-ui/slider/index)** will be used in **[Funnel charts demo](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/funnel-charts/basic-use.html)** - we do not have to expose it initially

![image](https://cloud.githubusercontent.com/assets/2712405/11915467/a642d30e-a675-11e5-81ad-4669f5b38a52.png)

**Comment by JeroenVinke** [comment] 2015-12-23 18:18
duplicate of https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/169

**Closed by JeroenVinke** 2015-12-23 18:18 UTC
Labels: sample
